CREATE TABLE ingredients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(1000),
    default_unit VARCHAR(30) NOT NULL,
    calories_kcal NUMERIC(10, 2),
    protein_grams NUMERIC(10, 2),
    carbohydrate_grams NUMERIC(10, 2),
    fat_grams NUMERIC(10, 2),
    fiber_grams NUMERIC(10, 2),
    sodium_milligrams NUMERIC(10, 2),
    season_start_month INTEGER,
    season_end_month INTEGER,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_ingredients_season_months CHECK (
        (season_start_month IS NULL AND season_end_month IS NULL)
        OR (season_start_month BETWEEN 1 AND 12 AND season_end_month BETWEEN 1 AND 12)
    ),
    CONSTRAINT ck_ingredients_nutrition_non_negative CHECK (
        (calories_kcal IS NULL OR calories_kcal >= 0)
        AND (protein_grams IS NULL OR protein_grams >= 0)
        AND (carbohydrate_grams IS NULL OR carbohydrate_grams >= 0)
        AND (fat_grams IS NULL OR fat_grams >= 0)
        AND (fiber_grams IS NULL OR fiber_grams >= 0)
        AND (sodium_milligrams IS NULL OR sodium_milligrams >= 0)
    )
);

CREATE UNIQUE INDEX uk_ingredients_name_lower ON ingredients (LOWER(name));
