CREATE TABLE recipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(160) NOT NULL,
    description VARCHAR(1500),
    servings INTEGER NOT NULL,
    preparation_time_minutes INTEGER NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_recipes_servings_positive CHECK (servings > 0),
    CONSTRAINT ck_recipes_preparation_time_non_negative CHECK (preparation_time_minutes >= 0)
);

CREATE UNIQUE INDEX uk_recipes_name_lower ON recipes (LOWER(name));

CREATE TABLE recipe_ingredients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id BIGINT NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
    ingredient_id BIGINT NOT NULL REFERENCES ingredients(id) ON DELETE RESTRICT,
    position INTEGER NOT NULL,
    quantity NUMERIC(12, 3) NOT NULL,
    unit VARCHAR(30) NOT NULL,
    notes VARCHAR(500),
    CONSTRAINT ck_recipe_ingredients_position_positive CHECK (position > 0),
    CONSTRAINT ck_recipe_ingredients_quantity_positive CHECK (quantity > 0),
    CONSTRAINT uk_recipe_ingredients_position UNIQUE (recipe_id, position)
);

CREATE INDEX ix_recipe_ingredients_ingredient_id ON recipe_ingredients (ingredient_id);

CREATE TABLE recipe_steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id BIGINT NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
    position INTEGER NOT NULL,
    instruction VARCHAR(2000) NOT NULL,
    CONSTRAINT ck_recipe_steps_position_positive CHECK (position > 0),
    CONSTRAINT uk_recipe_steps_position UNIQUE (recipe_id, position)
);
