-- Catálogo inicial do EuChef. Valores nutricionais são referências médias aproximadas por 100 g;
-- variam por marca, variedade, maturação e preparo e não substituem orientação profissional.
INSERT INTO ingredients (name, description, default_unit, calories_kcal, protein_grams, carbohydrate_grams, fat_grams, fiber_grams, sodium_milligrams)
VALUES    ('Berinjela', 'Ingrediente culinário usado em Ratatouille provençal. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 25, 1.0, 6.0, 0.2, 3.0, 2),
    ('Abobrinha italiana', 'Ingrediente culinário usado em Ratatouille provençal. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 17, 1.2, 3.1, 0.3, 1.0, 8),
    ('Tomate italiano', 'Ingrediente culinário usado em Ratatouille provençal. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 18, 0.9, 3.9, 0.2, 1.2, 5),
    ('Pimentão vermelho', 'Ingrediente culinário usado em Ratatouille provençal. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 31, 1.0, 6.0, 0.3, 2.1, 4),
    ('Cebola amarela', 'Ingrediente culinário usado em Ratatouille provençal. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 40, 1.1, 9.3, 0.1, 1.7, 4),
    ('Alho', 'Ingrediente culinário usado em Ratatouille provençal. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 149, 6.4, 33.1, 0.5, 2.1, 17),
    ('Azeite de oliva', 'Ingrediente culinário usado em Ratatouille provençal. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'MILLILITER', 884, 0.0, 0.0, 100.0, 0.0, 2),
    ('Abóbora cabotiá', 'Ingrediente culinário usado em Sopa rústica de raízes. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 48, 1.4, 10.8, 0.7, 2.6, 1),
    ('Cenoura', 'Ingrediente culinário usado em Sopa rústica de raízes. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 41, 0.9, 9.6, 0.2, 2.8, 69),
    ('Batata inglesa', 'Ingrediente culinário usado em Sopa rústica de raízes. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 77, 2.0, 17.5, 0.1, 2.2, 6),
    ('Batata-doce', 'Ingrediente culinário usado em Sopa rústica de raízes. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 86, 1.6, 20.1, 0.1, 3.0, 55),
    ('Alho-poró', 'Ingrediente culinário usado em Sopa rústica de raízes. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 61, 1.5, 14.2, 0.3, 1.8, 20),
    ('Salsão', 'Ingrediente culinário usado em Sopa rústica de raízes. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 14, 0.7, 3.0, 0.2, 1.6, 80),
    ('Gengibre fresco', 'Ingrediente culinário usado em Sopa rústica de raízes. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 80, 1.8, 17.8, 0.8, 2.0, 13),
    ('Alface crespa', 'Ingrediente culinário usado em Salada verde crocante. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 15, 1.4, 2.9, 0.2, 1.3, 28),
    ('Rúcula', 'Ingrediente culinário usado em Salada verde crocante. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 25, 2.6, 3.7, 0.7, 1.6, 27),
    ('Espinafre', 'Ingrediente culinário usado em Salada verde crocante. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 23, 2.9, 3.6, 0.4, 2.2, 79),
    ('Pepino japonês', 'Ingrediente culinário usado em Salada verde crocante. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 15, 0.7, 3.6, 0.1, 0.5, 2),
    ('Rabanete', 'Ingrediente culinário usado em Salada verde crocante. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 16, 0.7, 3.4, 0.1, 1.6, 39),
    ('Beterraba', 'Ingrediente culinário usado em Salada verde crocante. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 43, 1.6, 9.6, 0.2, 2.8, 78),
    ('Agrião', 'Ingrediente culinário usado em Salada verde crocante. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 11, 2.3, 1.3, 0.1, 0.5, 41),
    ('Brócolis', 'Ingrediente culinário usado em Legumes salteados orientais. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 34, 2.8, 6.6, 0.4, 2.6, 33),
    ('Couve-flor', 'Ingrediente culinário usado em Legumes salteados orientais. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 25, 1.9, 5.0, 0.3, 2.0, 30),
    ('Repolho verde', 'Ingrediente culinário usado em Legumes salteados orientais. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 25, 1.3, 5.8, 0.1, 2.5, 18),
    ('Vagem', 'Ingrediente culinário usado em Legumes salteados orientais. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 31, 1.8, 7.0, 0.2, 2.7, 6),
    ('Ervilha fresca', 'Ingrediente culinário usado em Legumes salteados orientais. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 81, 5.4, 14.5, 0.4, 5.1, 5),
    ('Milho-verde', 'Ingrediente culinário usado em Legumes salteados orientais. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 86, 3.3, 19.0, 1.4, 2.7, 15),
    ('Cogumelo paris', 'Ingrediente culinário usado em Legumes salteados orientais. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 22, 3.1, 3.3, 0.3, 1.0, 5),
    ('Banana-prata', 'Ingrediente culinário usado em Salada de frutas tropical. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 98, 1.3, 26.0, 0.1, 2.0, 0),
    ('Maçã fuji', 'Ingrediente culinário usado em Salada de frutas tropical. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 63, 0.2, 15.2, 0.2, 2.1, 1),
    ('Laranja pera', 'Ingrediente culinário usado em Salada de frutas tropical. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 37, 1.0, 8.9, 0.1, 0.8, 0),
    ('Mamão papaia', 'Ingrediente culinário usado em Salada de frutas tropical. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 43, 0.5, 10.8, 0.3, 1.7, 8),
    ('Manga palmer', 'Ingrediente culinário usado em Salada de frutas tropical. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 60, 0.8, 15.0, 0.4, 1.6, 1),
    ('Abacaxi', 'Ingrediente culinário usado em Salada de frutas tropical. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 50, 0.5, 13.1, 0.1, 1.4, 1),
    ('Uva sem semente', 'Ingrediente culinário usado em Salada de frutas tropical. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 69, 0.7, 18.1, 0.2, 0.9, 2),
    ('Morango', 'Ingrediente culinário usado em Iogurte com frutas vermelhas. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 32, 0.7, 7.7, 0.3, 2.0, 1),
    ('Mirtilo', 'Ingrediente culinário usado em Iogurte com frutas vermelhas. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 57, 0.7, 14.5, 0.3, 2.4, 1),
    ('Framboesa', 'Ingrediente culinário usado em Iogurte com frutas vermelhas. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 52, 1.2, 11.9, 0.7, 6.5, 1),
    ('Amora', 'Ingrediente culinário usado em Iogurte com frutas vermelhas. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 43, 1.4, 9.6, 0.5, 5.3, 1),
    ('Iogurte natural', 'Ingrediente culinário usado em Iogurte com frutas vermelhas. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 61, 3.5, 4.7, 3.3, 0.0, 46),
    ('Mel', 'Ingrediente culinário usado em Iogurte com frutas vermelhas. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 304, 0.3, 82.4, 0.0, 0.2, 4),
    ('Semente de chia', 'Ingrediente culinário usado em Iogurte com frutas vermelhas. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 486, 16.5, 42.1, 30.7, 34.4, 16),
    ('Aveia em flocos', 'Ingrediente culinário usado em Mingau de aveia com pera. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 379, 13.2, 67.7, 6.5, 10.1, 6),
    ('Leite integral', 'Ingrediente culinário usado em Mingau de aveia com pera. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'MILLILITER', 61, 3.2, 4.8, 3.3, 0.0, 43),
    ('Canela em pó', 'Ingrediente culinário usado em Mingau de aveia com pera. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 247, 4.0, 80.6, 1.2, 53.1, 10),
    ('Pera', 'Ingrediente culinário usado em Mingau de aveia com pera. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 57, 0.4, 15.2, 0.1, 3.1, 1),
    ('Noz', 'Ingrediente culinário usado em Mingau de aveia com pera. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 654, 15.2, 13.7, 65.2, 6.7, 2),
    ('Linhaça dourada', 'Ingrediente culinário usado em Mingau de aveia com pera. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 534, 18.3, 28.9, 42.2, 27.3, 30),
    ('Uva-passa', 'Ingrediente culinário usado em Mingau de aveia com pera. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 299, 3.1, 79.2, 0.5, 3.7, 11),
    ('Quinoa', 'Ingrediente culinário usado em Tabule de quinoa. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 368, 14.1, 64.2, 6.1, 7.0, 5),
    ('Salsinha', 'Ingrediente culinário usado em Tabule de quinoa. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 36, 3.0, 6.3, 0.8, 3.3, 56),
    ('Hortelã', 'Ingrediente culinário usado em Tabule de quinoa. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 44, 3.3, 8.4, 0.7, 6.8, 30),
    ('Tomate-cereja', 'Ingrediente culinário usado em Tabule de quinoa. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 18, 0.9, 3.9, 0.2, 1.2, 5),
    ('Cebola roxa', 'Ingrediente culinário usado em Tabule de quinoa. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 40, 1.1, 9.3, 0.1, 1.7, 4),
    ('Limão-siciliano', 'Ingrediente culinário usado em Tabule de quinoa. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 29, 1.1, 9.3, 0.3, 2.8, 2),
    ('Romã', 'Ingrediente culinário usado em Tabule de quinoa. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 83, 1.7, 18.7, 1.2, 4.0, 3),
    ('Lentilha marrom', 'Ingrediente culinário usado em Curry de lentilha. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 353, 25.8, 60.1, 1.1, 10.7, 6),
    ('Leite de coco', 'Ingrediente culinário usado em Curry de lentilha. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'MILLILITER', 197, 2.0, 2.8, 21.3, 0.0, 15),
    ('Cúrcuma', 'Ingrediente culinário usado em Curry de lentilha. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 312, 9.7, 67.1, 3.3, 22.7, 27),
    ('Cominho em pó', 'Ingrediente culinário usado em Curry de lentilha. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 375, 17.8, 44.2, 22.3, 10.5, 168),
    ('Coentro em grão', 'Ingrediente culinário usado em Curry de lentilha. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 298, 12.4, 55.0, 17.8, 41.9, 35),
    ('Garam masala', 'Ingrediente culinário usado em Curry de lentilha. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 350, 13.0, 58.0, 14.0, 23.0, 80),
    ('Arroz integral', 'Ingrediente culinário usado em Curry de lentilha. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 370, 7.9, 77.2, 2.9, 3.5, 7),
    ('Feijão-preto', 'Ingrediente culinário usado em Feijão-preto com acompanhamentos. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 339, 21.6, 62.4, 0.9, 15.5, 5),
    ('Linguiça calabresa', 'Ingrediente culinário usado em Feijão-preto com acompanhamentos. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 320, 16.0, 2.5, 27.0, 0.0, 1100),
    ('Couve-manteiga', 'Ingrediente culinário usado em Feijão-preto com acompanhamentos. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 32, 3.0, 5.4, 0.6, 4.0, 18),
    ('Farinha de mandioca', 'Ingrediente culinário usado em Feijão-preto com acompanhamentos. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 365, 1.6, 89.2, 0.3, 6.4, 1),
    ('Folha de louro', 'Ingrediente culinário usado em Feijão-preto com acompanhamentos. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 313, 7.6, 75.0, 8.4, 26.3, 23),
    ('Bacon', 'Ingrediente culinário usado em Feijão-preto com acompanhamentos. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 541, 37.0, 1.4, 42.0, 0.0, 1717),
    ('Pimenta dedo-de-moça', 'Ingrediente culinário usado em Feijão-preto com acompanhamentos. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 40, 1.9, 8.8, 0.4, 1.5, 9),
    ('Peito de frango', 'Ingrediente culinário usado em Frango assado com mostarda. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 120, 22.5, 0.0, 2.6, 0.0, 45),
    ('Alecrim', 'Ingrediente culinário usado em Frango assado com mostarda. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 131, 3.3, 20.7, 5.9, 14.1, 26),
    ('Tomilho', 'Ingrediente culinário usado em Frango assado com mostarda. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 101, 5.6, 24.5, 1.7, 14.0, 9),
    ('Vinho branco seco', 'Ingrediente culinário usado em Frango assado com mostarda. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'MILLILITER', 82, 0.1, 2.6, 0.0, 0.0, 5),
    ('Mostarda dijon', 'Ingrediente culinário usado em Frango assado com mostarda. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 120, 6.0, 5.7, 7.0, 3.3, 1200),
    ('Batata bolinha', 'Ingrediente culinário usado em Frango assado com mostarda. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 77, 2.0, 17.5, 0.1, 2.2, 6),
    ('Manteiga sem sal', 'Ingrediente culinário usado em Frango assado com mostarda. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 717, 0.9, 0.1, 81.1, 0.0, 11),
    ('Acém bovino', 'Ingrediente culinário usado em Carne de panela com mandioca. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 215, 19.0, 0.0, 15.0, 0.0, 55),
    ('Mandioca', 'Ingrediente culinário usado em Carne de panela com mandioca. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 160, 1.4, 38.1, 0.3, 1.8, 14),
    ('Quiabo', 'Ingrediente culinário usado em Carne de panela com mandioca. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 33, 1.9, 7.5, 0.2, 3.2, 7),
    ('Extrato de tomate', 'Ingrediente culinário usado em Carne de panela com mandioca. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 82, 4.3, 18.9, 0.5, 4.1, 59),
    ('Molho inglês', 'Ingrediente culinário usado em Carne de panela com mandioca. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'MILLILITER', 78, 0.0, 19.5, 0.0, 0.0, 980),
    ('Páprica doce', 'Ingrediente culinário usado em Carne de panela com mandioca. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 282, 14.1, 54.0, 13.0, 34.9, 68),
    ('Caldo de carne', 'Ingrediente culinário usado em Carne de panela com mandioca. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'MILLILITER', 7, 1.1, 0.2, 0.2, 0.0, 350),
    ('Filé de peixe branco', 'Ingrediente culinário usado em Moqueca de peixe e camarão. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 96, 20.1, 0.0, 1.7, 0.0, 52),
    ('Camarão', 'Ingrediente culinário usado em Moqueca de peixe e camarão. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 85, 20.0, 0.0, 0.5, 0.0, 119),
    ('Óleo de coco', 'Ingrediente culinário usado em Moqueca de peixe e camarão. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'MILLILITER', 892, 0.0, 0.0, 100.0, 0.0, 0),
    ('Azeite de dendê', 'Ingrediente culinário usado em Moqueca de peixe e camarão. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'MILLILITER', 884, 0.0, 0.0, 100.0, 0.0, 0),
    ('Pimentão amarelo', 'Ingrediente culinário usado em Moqueca de peixe e camarão. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 27, 1.0, 6.3, 0.2, 0.9, 2),
    ('Coentro fresco', 'Ingrediente culinário usado em Moqueca de peixe e camarão. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 23, 2.1, 3.7, 0.5, 2.8, 46),
    ('Limão-taiti', 'Ingrediente culinário usado em Moqueca de peixe e camarão. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 30, 0.7, 10.5, 0.2, 2.8, 2),
    ('Salmão', 'Ingrediente culinário usado em Salmão com cevada e aspargos. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 208, 20.4, 0.0, 13.4, 0.0, 59),
    ('Aspargo', 'Ingrediente culinário usado em Salmão com cevada e aspargos. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 20, 2.2, 3.9, 0.1, 2.1, 2),
    ('Endro', 'Ingrediente culinário usado em Salmão com cevada e aspargos. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 43, 3.5, 7.0, 1.1, 2.1, 61),
    ('Alcaparra', 'Ingrediente culinário usado em Salmão com cevada e aspargos. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 23, 2.4, 4.9, 0.9, 3.2, 2960),
    ('Iogurte grego', 'Ingrediente culinário usado em Salmão com cevada e aspargos. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'MILLILITER', 97, 9.0, 3.9, 5.0, 0.0, 36),
    ('Alho em pó', 'Ingrediente culinário usado em Salmão com cevada e aspargos. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 331, 16.6, 72.7, 0.7, 9.0, 60),
    ('Cevada em grãos', 'Ingrediente culinário usado em Salmão com cevada e aspargos. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 354, 12.5, 73.5, 2.3, 17.3, 12),
    ('Espaguete', 'Ingrediente culinário usado em Espaguete ao pesto. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 371, 13.0, 74.7, 1.5, 3.2, 6),
    ('Manjericão', 'Ingrediente culinário usado em Espaguete ao pesto. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 23, 3.2, 2.7, 0.6, 1.6, 4),
    ('Pinoli', 'Ingrediente culinário usado em Espaguete ao pesto. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 673, 13.7, 13.1, 68.4, 3.7, 2),
    ('Queijo parmesão', 'Ingrediente culinário usado em Espaguete ao pesto. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 431, 38.0, 4.1, 29.0, 0.0, 1529),
    ('Azeite extravirgem', 'Ingrediente culinário usado em Espaguete ao pesto. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'MILLILITER', 884, 0.0, 0.0, 100.0, 0.0, 2),
    ('Pimenta-do-reino', 'Ingrediente culinário usado em Espaguete ao pesto. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 251, 10.4, 64.0, 3.3, 25.3, 20),
    ('Queijo pecorino', 'Ingrediente culinário usado em Espaguete ao pesto. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 387, 31.9, 3.6, 26.9, 0.0, 1200),
    ('Massa para lasanha', 'Ingrediente culinário usado em Lasanha à bolonhesa. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 371, 13.0, 74.7, 1.5, 3.2, 6),
    ('Carne moída bovina', 'Ingrediente culinário usado em Lasanha à bolonhesa. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 212, 19.0, 0.0, 15.0, 0.0, 66),
    ('Ricota', 'Ingrediente culinário usado em Lasanha à bolonhesa. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 140, 12.6, 3.8, 8.1, 0.0, 84),
    ('Muçarela', 'Ingrediente culinário usado em Lasanha à bolonhesa. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 300, 22.2, 2.2, 22.4, 0.0, 627),
    ('Molho de tomate', 'Ingrediente culinário usado em Lasanha à bolonhesa. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'MILLILITER', 38, 1.4, 7.3, 0.9, 1.5, 420),
    ('Orégano', 'Ingrediente culinário usado em Lasanha à bolonhesa. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 265, 9.0, 68.9, 4.3, 42.5, 25),
    ('Noz-moscada', 'Ingrediente culinário usado em Lasanha à bolonhesa. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 525, 5.8, 49.0, 36.3, 20.8, 16),
    ('Arroz arbóreo', 'Ingrediente culinário usado em Risoto de cogumelos. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 358, 6.8, 79.0, 0.8, 1.0, 5),
    ('Cogumelo portobello', 'Ingrediente culinário usado em Risoto de cogumelos. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 22, 2.1, 3.9, 0.4, 1.3, 9),
    ('Caldo de legumes', 'Ingrediente culinário usado em Risoto de cogumelos. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'MILLILITER', 6, 0.2, 1.0, 0.1, 0.0, 340),
    ('Vinho branco culinário', 'Ingrediente culinário usado em Risoto de cogumelos. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'MILLILITER', 81, 0.1, 5.9, 0.0, 0.0, 626),
    ('Chalota', 'Ingrediente culinário usado em Risoto de cogumelos. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 72, 2.5, 16.8, 0.1, 3.2, 12),
    ('Queijo grana padano', 'Ingrediente culinário usado em Risoto de cogumelos. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 398, 33.0, 0.0, 29.0, 0.0, 600),
    ('Sálvia', 'Ingrediente culinário usado em Risoto de cogumelos. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 315, 10.6, 60.7, 12.8, 40.3, 11),
    ('Arroz bomba', 'Ingrediente culinário usado em Paella de frutos do mar. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 360, 6.7, 79.3, 0.6, 1.4, 5),
    ('Lula', 'Ingrediente culinário usado em Paella de frutos do mar. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 92, 15.6, 3.1, 1.4, 0.0, 44),
    ('Mexilhão', 'Ingrediente culinário usado em Paella de frutos do mar. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 86, 11.9, 3.7, 2.2, 0.0, 286),
    ('Chouriço espanhol', 'Ingrediente culinário usado em Paella de frutos do mar. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 455, 24.1, 1.9, 38.3, 0.0, 1235),
    ('Açafrão', 'Ingrediente culinário usado em Paella de frutos do mar. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 310, 11.4, 65.4, 5.9, 3.9, 148),
    ('Caldo de frutos do mar', 'Caldo culinário usado em Paella de frutos do mar. Valores nutricionais médios aproximados por 100 g; podem variar conforme receita e teor de sal.', 'MILLILITER', 12, 1.5, 0.8, 0.3, 0.0, 380),
    ('Páprica defumada', 'Ingrediente culinário usado em Paella de frutos do mar. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 282, 14.1, 54.0, 12.9, 34.9, 68),
    ('Ovo de galinha', 'Ingrediente culinário usado em Omelete de presunto e queijo. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 143, 12.6, 0.7, 9.5, 0.0, 142),
    ('Presunto cozido', 'Ingrediente culinário usado em Omelete de presunto e queijo. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 145, 20.9, 1.5, 5.5, 0.0, 1203),
    ('Queijo cheddar', 'Ingrediente culinário usado em Omelete de presunto e queijo. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 403, 22.9, 3.4, 33.1, 0.0, 653),
    ('Cebolinha', 'Ingrediente culinário usado em Omelete de presunto e queijo. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 30, 3.3, 4.4, 0.7, 3.9, 3),
    ('Tomate seco', 'Ingrediente culinário usado em Omelete de presunto e queijo. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 258, 14.1, 55.8, 3.0, 12.3, 107),
    ('Creme de leite', 'Ingrediente culinário usado em Omelete de presunto e queijo. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'MILLILITER', 340, 2.1, 2.8, 36.1, 0.0, 27),
    ('Óleo de canola', 'Ingrediente culinário usado em Omelete de presunto e queijo. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'MILLILITER', 884, 0.0, 0.0, 100.0, 0.0, 0),
    ('Farinha de trigo', 'Ingrediente culinário usado em Panqueca americana. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 364, 10.3, 76.3, 1.0, 2.7, 2),
    ('Fermento químico', 'Ingrediente culinário usado em Panqueca americana. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 53, 0.0, 27.7, 0.0, 0.2, 10600),
    ('Açúcar refinado', 'Ingrediente culinário usado em Panqueca americana. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 387, 0.0, 100.0, 0.0, 0.0, 1),
    ('Extrato de baunilha', 'Ingrediente culinário usado em Panqueca americana. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 288, 0.1, 12.7, 0.1, 0.0, 9),
    ('Leitelho', 'Ingrediente culinário usado em Panqueca americana. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'MILLILITER', 40, 3.3, 4.8, 0.9, 0.0, 105),
    ('Óleo de girassol', 'Ingrediente culinário usado em Panqueca americana. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'MILLILITER', 884, 0.0, 0.0, 100.0, 0.0, 0),
    ('Xarope de bordo', 'Ingrediente culinário usado em Panqueca americana. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'MILLILITER', 260, 0.0, 67.0, 0.1, 0.0, 12),
    ('Farinha de trigo integral', 'Ingrediente culinário usado em Pão integral com sementes. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 340, 13.2, 72.0, 2.5, 10.7, 5),
    ('Fermento biológico seco', 'Ingrediente culinário usado em Pão integral com sementes. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 325, 40.4, 41.2, 7.6, 26.9, 51),
    ('Água', 'Ingrediente culinário usado em Pão integral com sementes. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'MILLILITER', 0, 0.0, 0.0, 0.0, 0.0, 0),
    ('Sal marinho', 'Ingrediente culinário usado em Pão integral com sementes. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 0, 0.0, 0.0, 0.0, 0.0, 38758),
    ('Gergelim', 'Ingrediente culinário usado em Pão integral com sementes. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 573, 17.7, 23.4, 49.7, 11.8, 11),
    ('Semente de girassol', 'Ingrediente culinário usado em Pão integral com sementes. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 584, 20.8, 20.0, 51.5, 8.6, 9),
    ('Feijão-branco', 'Ingrediente culinário usado em Pasta de feijão-branco. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 333, 23.4, 60.3, 0.9, 15.2, 16),
    ('Tahine', 'Ingrediente culinário usado em Pasta de feijão-branco. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 595, 17.0, 21.2, 53.8, 9.3, 115),
    ('Páprica picante', 'Ingrediente culinário usado em Pasta de feijão-branco. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 282, 14.1, 54.0, 12.9, 34.9, 68),
    ('Vinagre de maçã', 'Ingrediente culinário usado em Pasta de feijão-branco. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'MILLILITER', 21, 0.0, 0.9, 0.0, 0.0, 5),
    ('Za''atar', 'Ingrediente culinário usado em Pasta de feijão-branco. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 360, 12.0, 44.0, 18.0, 20.0, 2100),
    ('Óleo de abacate', 'Ingrediente culinário usado em Pasta de feijão-branco. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'MILLILITER', 884, 0.0, 0.0, 100.0, 0.0, 0),
    ('Abacate', 'Ingrediente culinário usado em Guacamole com tortilhas. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 160, 2.0, 8.5, 14.7, 6.7, 7),
    ('Pimenta jalapeño', 'Ingrediente culinário usado em Guacamole com tortilhas. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 29, 0.9, 6.5, 0.4, 2.8, 3),
    ('Cebola branca', 'Ingrediente culinário usado em Guacamole com tortilhas. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 40, 1.1, 9.3, 0.1, 1.7, 4),
    ('Tomatillo', 'Ingrediente culinário usado em Guacamole com tortilhas. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 32, 1.0, 5.8, 1.0, 1.9, 1),
    ('Semente de abóbora', 'Ingrediente culinário usado em Guacamole com tortilhas. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 559, 30.2, 10.7, 49.1, 6.0, 7),
    ('Tortilha de milho', 'Ingrediente culinário usado em Guacamole com tortilhas. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 218, 5.7, 44.6, 2.9, 6.3, 45),
    ('Tofu firme', 'Ingrediente culinário usado em Curry de tofu com macarrão de arroz. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 144, 17.3, 2.8, 8.7, 2.3, 14),
    ('Acelga chinesa', 'Ingrediente culinário usado em Curry de tofu com macarrão de arroz. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 13, 1.5, 2.2, 0.2, 1.0, 65),
    ('Broto de bambu', 'Ingrediente culinário usado em Curry de tofu com macarrão de arroz. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 27, 2.6, 5.2, 0.3, 2.2, 4),
    ('Missô', 'Ingrediente culinário usado em Curry de tofu com macarrão de arroz. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 199, 12.8, 26.5, 6.0, 5.4, 3728),
    ('Vinagre de arroz', 'Ingrediente culinário usado em Curry de tofu com macarrão de arroz. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'MILLILITER', 18, 0.0, 0.0, 0.0, 0.0, 5),
    ('Macarrão de arroz', 'Ingrediente culinário usado em Curry de tofu com macarrão de arroz. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 364, 6.0, 80.2, 0.6, 1.6, 182),
    ('Lombo suíno', 'Ingrediente culinário usado em Lombo suíno agridoce. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 143, 21.0, 0.0, 4.0, 0.0, 56),
    ('Pêssego em conserva', 'Ingrediente culinário usado em Lombo suíno agridoce. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 74, 0.5, 19.0, 0.1, 1.3, 3),
    ('Ervilha-torta', 'Ingrediente culinário usado em Lombo suíno agridoce. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 42, 2.8, 7.6, 0.2, 2.6, 4),
    ('Ketchup', 'Ingrediente culinário usado em Lombo suíno agridoce. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'MILLILITER', 112, 1.3, 26.7, 0.2, 0.3, 907),
    ('Açúcar mascavo', 'Ingrediente culinário usado em Lombo suíno agridoce. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 380, 0.1, 98.1, 0.0, 0.0, 28),
    ('Amido de milho', 'Ingrediente culinário usado em Lombo suíno agridoce. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 381, 0.3, 91.3, 0.1, 0.9, 9),
    ('Pernil de cordeiro', 'Ingrediente culinário usado em Cuscuz marroquino com cordeiro. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 206, 18.6, 0.0, 14.4, 0.0, 65),
    ('Cuscuz marroquino', 'Ingrediente culinário usado em Cuscuz marroquino com cordeiro. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 376, 12.8, 77.4, 0.6, 5.0, 10),
    ('Damasco seco', 'Ingrediente culinário usado em Cuscuz marroquino com cordeiro. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 241, 3.4, 62.6, 0.5, 7.3, 10),
    ('Amêndoa', 'Ingrediente culinário usado em Cuscuz marroquino com cordeiro. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 579, 21.2, 21.6, 49.9, 12.5, 1),
    ('Ras el hanout', 'Ingrediente culinário usado em Cuscuz marroquino com cordeiro. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 302, 10.0, 49.0, 11.0, 24.0, 180),
    ('Harissa', 'Ingrediente culinário usado em Cuscuz marroquino com cordeiro. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 80, 2.0, 10.0, 4.0, 3.0, 1000),
    ('Atum em conserva', 'Ingrediente culinário usado em Sanduíche integral de atum. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 116, 25.5, 0.0, 0.8, 0.0, 247),
    ('Pão de forma integral', 'Ingrediente culinário usado em Sanduíche integral de atum. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 247, 12.5, 41.4, 4.2, 6.8, 450),
    ('Maionese', 'Ingrediente culinário usado em Sanduíche integral de atum. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'MILLILITER', 680, 1.0, 0.6, 75.0, 0.0, 635),
    ('Pepino em conserva', 'Ingrediente culinário usado em Sanduíche integral de atum. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 12, 0.5, 2.4, 0.3, 1.0, 1208),
    ('Alface romana', 'Ingrediente culinário usado em Sanduíche integral de atum. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 17, 1.2, 3.3, 0.3, 2.1, 8),
    ('Queijo provolone', 'Ingrediente culinário usado em Sanduíche integral de atum. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 351, 25.6, 2.1, 26.6, 0.0, 876),
    ('Cacau em pó', 'Ingrediente culinário usado em Bolo de chocolate sem trigo. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 228, 19.6, 57.9, 13.7, 37.0, 21),
    ('Chocolate amargo', 'Ingrediente culinário usado em Bolo de chocolate sem trigo. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 598, 7.8, 45.9, 42.6, 10.9, 20),
    ('Farinha de amêndoa', 'Ingrediente culinário usado em Bolo de chocolate sem trigo. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 571, 21.4, 21.4, 50.0, 10.7, 18),
    ('Açúcar de coco', 'Ingrediente culinário usado em Bolo de chocolate sem trigo. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 375, 1.0, 92.0, 0.0, 1.0, 45),
    ('Creme de coco', 'Ingrediente culinário usado em Bolo de chocolate sem trigo. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'MILLILITER', 330, 3.6, 6.7, 34.7, 2.2, 20),
    ('Bicarbonato de sódio', 'Ingrediente culinário usado em Bolo de chocolate sem trigo. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 0, 0.0, 0.0, 0.0, 0.0, 27360),
    ('Cream cheese', 'Ingrediente culinário usado em Cheesecake de maracujá. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 342, 5.9, 4.1, 34.2, 0.0, 321),
    ('Biscoito integral', 'Ingrediente culinário usado em Cheesecake de maracujá. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 443, 8.0, 69.0, 15.0, 6.0, 500),
    ('Leite condensado', 'Ingrediente culinário usado em Cheesecake de maracujá. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'MILLILITER', 321, 7.9, 54.4, 8.7, 0.0, 127),
    ('Maracujá', 'Ingrediente culinário usado em Cheesecake de maracujá. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'UNIT', 97, 2.2, 23.4, 0.7, 10.4, 28),
    ('Gelatina incolor', 'Ingrediente culinário usado em Cheesecake de maracujá. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 335, 85.6, 0.0, 0.1, 0.0, 196),
    ('Castanha de caju', 'Ingrediente culinário usado em Cheesecake de maracujá. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 553, 18.2, 30.2, 43.9, 3.3, 12),
    ('Feijão-vermelho', 'Ingrediente culinário usado em Chili vegetariano. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 337, 22.5, 61.3, 1.1, 15.2, 12),
    ('Feijão-carioca', 'Ingrediente culinário usado em Chili vegetariano. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 329, 20.0, 61.2, 1.3, 18.4, 14),
    ('Trigo para quibe', 'Ingrediente culinário usado em Chili vegetariano. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'GRAM', 342, 12.3, 75.9, 1.3, 12.5, 17),
    ('Pimenta chipotle', 'Ingrediente culinário usado em Chili vegetariano. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 282, 13.0, 50.0, 14.7, 34.8, 90),
    ('Cerveja escura', 'Ingrediente culinário usado em Chili vegetariano. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'MILLILITER', 43, 0.5, 3.6, 0.0, 0.0, 4),
    ('Levedura nutricional', 'Ingrediente culinário usado em Chili vegetariano. Valores nutricionais médios aproximados por 100 g; podem variar conforme origem e preparo.', 'TEASPOON', 357, 50.0, 35.7, 7.1, 21.4, 357)
ON CONFLICT (LOWER(name)) DO NOTHING;

CREATE TEMP TABLE euchef_inserted_seed_recipes (id BIGINT PRIMARY KEY, name VARCHAR(160) NOT NULL) ON COMMIT DROP;

WITH inserted AS (
    INSERT INTO recipes (name, description, servings, preparation_time_minutes)
    VALUES
        ('Ratatouille provençal', 'Legumes assados lentamente com ervas mediterrâneas.', 6, 70),
        ('Sopa rústica de raízes', 'Sopa cremosa e reconfortante de hortaliças e raízes.', 6, 55),
        ('Salada verde crocante', 'Salada fresca com folhas, pepino e raízes.', 4, 20),
        ('Legumes salteados orientais', 'Mix colorido de legumes salteados e cogumelos.', 4, 30),
        ('Salada de frutas tropical', 'Frutas frescas variadas servidas geladas.', 8, 20),
        ('Iogurte com frutas vermelhas', 'Taça de iogurte, frutas, mel e sementes.', 4, 10),
        ('Mingau de aveia com pera', 'Café da manhã quente com aveia, fruta e sementes.', 4, 20),
        ('Tabule de quinoa', 'Salada de quinoa com ervas frescas e romã.', 6, 35),
        ('Curry de lentilha', 'Ensopado aromático de lentilha com leite de coco.', 6, 50),
        ('Feijão-preto com acompanhamentos', 'Feijão encorpado com carnes e acompanhamentos brasileiros.', 8, 120),
        ('Frango assado com mostarda', 'Peito de frango assado com ervas, vinho e batatas.', 6, 65),
        ('Carne de panela com mandioca', 'Carne bovina cozida lentamente com mandioca e quiabo.', 8, 110),
        ('Moqueca de peixe e camarão', 'Ensopado brasileiro de peixe, camarão e coco.', 6, 55),
        ('Salmão com cevada e aspargos', 'Salmão assado acompanhado de cevada e molho de iogurte.', 4, 50),
        ('Espaguete ao pesto', 'Massa com pesto de manjericão e queijos curados.', 6, 30),
        ('Lasanha à bolonhesa', 'Lasanha em camadas com carne, tomate e queijos.', 8, 90),
        ('Risoto de cogumelos', 'Arroz cremoso com cogumelos e queijo italiano.', 6, 45),
        ('Paella de frutos do mar', 'Arroz espanhol com frutos do mar e açafrão.', 8, 60),
        ('Omelete de presunto e queijo', 'Omelete macia recheada com presunto, queijo e ervas.', 4, 20),
        ('Panqueca americana', 'Panquecas fofas para o café da manhã.', 6, 25),
        ('Pão integral com sementes', 'Pão caseiro de farinha integral e sementes.', 10, 150),
        ('Pasta de feijão-branco', 'Pasta vegetal cremosa com tahine e especiarias.', 8, 25),
        ('Guacamole com tortilhas', 'Creme de abacate picante servido com tortilhas.', 6, 20),
        ('Curry de tofu com macarrão de arroz', 'Tofu e vegetais em molho fermentado com macarrão.', 4, 35),
        ('Lombo suíno agridoce', 'Carne suína com molho agridoce e ervilha-torta.', 6, 45),
        ('Cuscuz marroquino com cordeiro', 'Cuscuz aromático com cordeiro, frutas secas e especiarias.', 8, 80),
        ('Sanduíche integral de atum', 'Sanduíche frio de atum, folhas e queijo.', 4, 15),
        ('Bolo de chocolate sem trigo', 'Bolo úmido de chocolate com farinhas alternativas.', 10, 55),
        ('Cheesecake de maracujá', 'Sobremesa cremosa com base crocante e cobertura de fruta.', 10, 240),
        ('Chili vegetariano', 'Ensopado de feijões, trigo e temperos defumados.', 8, 60)
    ON CONFLICT (LOWER(name)) DO NOTHING
    RETURNING id, name
)
INSERT INTO euchef_inserted_seed_recipes (id, name) SELECT id, name FROM inserted;

INSERT INTO recipe_ingredients (recipe_id, ingredient_id, position, quantity, unit, notes)
SELECT recipe.id, ingredient.id, seed.position, seed.quantity, seed.unit, seed.notes
FROM (VALUES
    ('Ratatouille provençal', 'Berinjela', 1, 2, 'UNIT', 'médias, em rodelas'),
    ('Ratatouille provençal', 'Abobrinha italiana', 2, 2, 'UNIT', 'médias, em rodelas'),
    ('Ratatouille provençal', 'Tomate italiano', 3, 6, 'UNIT', 'maduros, em rodelas'),
    ('Ratatouille provençal', 'Pimentão vermelho', 4, 2, 'UNIT', 'sem sementes, fatiados'),
    ('Ratatouille provençal', 'Cebola amarela', 5, 1, 'UNIT', 'grande, fatiada'),
    ('Ratatouille provençal', 'Alho', 6, 4, 'UNIT', 'dentes picados'),
    ('Ratatouille provençal', 'Azeite de oliva', 7, 4, 'TABLESPOON', 'para regar e untar'),
    ('Sopa rústica de raízes', 'Abóbora cabotiá', 1, 800, 'GRAM', 'descascada, em cubos'),
    ('Sopa rústica de raízes', 'Cenoura', 2, 3, 'UNIT', 'médias, em rodelas'),
    ('Sopa rústica de raízes', 'Batata inglesa', 3, 3, 'UNIT', 'médias, em cubos'),
    ('Sopa rústica de raízes', 'Batata-doce', 4, 2, 'UNIT', 'médias, em cubos'),
    ('Sopa rústica de raízes', 'Alho-poró', 5, 1, 'UNIT', 'grande, fatiado'),
    ('Sopa rústica de raízes', 'Salsão', 6, 120, 'GRAM', 'talos picados'),
    ('Sopa rústica de raízes', 'Gengibre fresco', 7, 1, 'TABLESPOON', 'ralado'),
    ('Salada verde crocante', 'Alface crespa', 1, 150, 'GRAM', 'folhas rasgadas'),
    ('Salada verde crocante', 'Rúcula', 2, 80, 'GRAM', 'folhas higienizadas'),
    ('Salada verde crocante', 'Espinafre', 3, 80, 'GRAM', 'folhas jovens'),
    ('Salada verde crocante', 'Pepino japonês', 4, 2, 'UNIT', 'fatiados finamente'),
    ('Salada verde crocante', 'Rabanete', 5, 6, 'UNIT', 'fatiados finamente'),
    ('Salada verde crocante', 'Beterraba', 6, 1, 'UNIT', 'média, ralada'),
    ('Salada verde crocante', 'Agrião', 7, 80, 'GRAM', 'folhas e talos tenros'),
    ('Legumes salteados orientais', 'Brócolis', 1, 1, 'UNIT', 'cabeça média, em floretes'),
    ('Legumes salteados orientais', 'Couve-flor', 2, 0.5, 'UNIT', 'cabeça média, em floretes'),
    ('Legumes salteados orientais', 'Repolho verde', 3, 0.25, 'UNIT', 'cabeça média, fatiada'),
    ('Legumes salteados orientais', 'Vagem', 4, 150, 'GRAM', 'cortada ao meio'),
    ('Legumes salteados orientais', 'Ervilha fresca', 5, 120, 'GRAM', 'debulhada'),
    ('Legumes salteados orientais', 'Milho-verde', 6, 2, 'UNIT', 'espigas debulhadas'),
    ('Legumes salteados orientais', 'Cogumelo paris', 7, 200, 'GRAM', 'fatiado'),
    ('Salada de frutas tropical', 'Banana-prata', 1, 3, 'UNIT', 'em rodelas'),
    ('Salada de frutas tropical', 'Maçã fuji', 2, 2, 'UNIT', 'em cubos'),
    ('Salada de frutas tropical', 'Laranja pera', 3, 3, 'UNIT', 'em gomos sem pele'),
    ('Salada de frutas tropical', 'Mamão papaia', 4, 1, 'UNIT', 'grande, em cubos'),
    ('Salada de frutas tropical', 'Manga palmer', 5, 2, 'UNIT', 'médias, em cubos'),
    ('Salada de frutas tropical', 'Abacaxi', 6, 0.5, 'UNIT', 'médio, em cubos'),
    ('Salada de frutas tropical', 'Uva sem semente', 7, 300, 'GRAM', 'cortadas ao meio'),
    ('Iogurte com frutas vermelhas', 'Morango', 1, 120, 'GRAM', 'fatiado'),
    ('Iogurte com frutas vermelhas', 'Mirtilo', 2, 80, 'GRAM', 'inteiro'),
    ('Iogurte com frutas vermelhas', 'Framboesa', 3, 80, 'GRAM', 'inteira'),
    ('Iogurte com frutas vermelhas', 'Amora', 4, 80, 'GRAM', 'inteira'),
    ('Iogurte com frutas vermelhas', 'Iogurte natural', 5, 600, 'GRAM', 'dividido entre as taças'),
    ('Iogurte com frutas vermelhas', 'Mel', 6, 2, 'TABLESPOON', 'para finalizar'),
    ('Iogurte com frutas vermelhas', 'Semente de chia', 7, 2, 'TABLESPOON', 'para finalizar'),
    ('Mingau de aveia com pera', 'Aveia em flocos', 1, 160, 'GRAM', 'flocos médios'),
    ('Mingau de aveia com pera', 'Leite integral', 2, 800, 'MILLILITER', 'para o cozimento'),
    ('Mingau de aveia com pera', 'Canela em pó', 3, 1, 'TEASPOON', 'mais um pouco para servir'),
    ('Mingau de aveia com pera', 'Pera', 4, 2, 'UNIT', 'maduras, em cubos'),
    ('Mingau de aveia com pera', 'Noz', 5, 40, 'GRAM', 'picada grosseiramente'),
    ('Mingau de aveia com pera', 'Linhaça dourada', 6, 2, 'TABLESPOON', 'moída'),
    ('Mingau de aveia com pera', 'Uva-passa', 7, 60, 'GRAM', 'sem sementes'),
    ('Tabule de quinoa', 'Quinoa', 1, 300, 'GRAM', 'crua, lavada'),
    ('Tabule de quinoa', 'Salsinha', 2, 1, 'CUP', 'folhas picadas'),
    ('Tabule de quinoa', 'Hortelã', 3, 0.5, 'CUP', 'folhas picadas'),
    ('Tabule de quinoa', 'Tomate-cereja', 4, 300, 'GRAM', 'cortado ao meio'),
    ('Tabule de quinoa', 'Cebola roxa', 5, 1, 'UNIT', 'média, picada'),
    ('Tabule de quinoa', 'Limão-siciliano', 6, 2, 'UNIT', 'suco e raspas'),
    ('Tabule de quinoa', 'Romã', 7, 1, 'UNIT', 'apenas os arilos'),
    ('Curry de lentilha', 'Lentilha marrom', 1, 400, 'GRAM', 'seca, lavada'),
    ('Curry de lentilha', 'Leite de coco', 2, 800, 'MILLILITER', 'para o molho'),
    ('Curry de lentilha', 'Cúrcuma', 3, 2, 'TEASPOON', 'em pó'),
    ('Curry de lentilha', 'Cominho em pó', 4, 2, 'TEASPOON', 'para o refogado'),
    ('Curry de lentilha', 'Coentro em grão', 5, 1.5, 'TEASPOON', 'levemente tostado e moído'),
    ('Curry de lentilha', 'Garam masala', 6, 2, 'TEASPOON', 'adicionado ao final'),
    ('Curry de lentilha', 'Arroz integral', 7, 360, 'GRAM', 'cru'),
    ('Feijão-preto com acompanhamentos', 'Feijão-preto', 1, 600, 'GRAM', 'seco, deixado de molho'),
    ('Feijão-preto com acompanhamentos', 'Linguiça calabresa', 2, 300, 'GRAM', 'em rodelas'),
    ('Feijão-preto com acompanhamentos', 'Couve-manteiga', 3, 300, 'GRAM', 'fatiada finamente'),
    ('Feijão-preto com acompanhamentos', 'Farinha de mandioca', 4, 250, 'GRAM', 'torrada, para acompanhar'),
    ('Feijão-preto com acompanhamentos', 'Folha de louro', 5, 3, 'UNIT', 'folhas inteiras'),
    ('Feijão-preto com acompanhamentos', 'Bacon', 6, 150, 'GRAM', 'em cubos'),
    ('Feijão-preto com acompanhamentos', 'Pimenta dedo-de-moça', 7, 1, 'UNIT', 'sem sementes, picada'),
    ('Frango assado com mostarda', 'Peito de frango', 1, 1.2, 'KILOGRAM', 'em filés grossos'),
    ('Frango assado com mostarda', 'Alecrim', 2, 1, 'TABLESPOON', 'folhas frescas picadas'),
    ('Frango assado com mostarda', 'Tomilho', 3, 2, 'TEASPOON', 'folhas frescas'),
    ('Frango assado com mostarda', 'Vinho branco seco', 4, 200, 'MILLILITER', 'para a marinada'),
    ('Frango assado com mostarda', 'Mostarda dijon', 5, 4, 'TABLESPOON', 'para a marinada'),
    ('Frango assado com mostarda', 'Batata bolinha', 6, 1, 'KILOGRAM', 'lavada e cortada ao meio'),
    ('Frango assado com mostarda', 'Manteiga sem sal', 7, 2, 'TABLESPOON', 'em pequenos pedaços'),
    ('Carne de panela com mandioca', 'Acém bovino', 1, 1.5, 'KILOGRAM', 'em cubos grandes'),
    ('Carne de panela com mandioca', 'Mandioca', 2, 1.2, 'KILOGRAM', 'descascada, em pedaços'),
    ('Carne de panela com mandioca', 'Quiabo', 3, 500, 'GRAM', 'em pedaços grandes'),
    ('Carne de panela com mandioca', 'Extrato de tomate', 4, 3, 'TABLESPOON', 'para encorpar o molho'),
    ('Carne de panela com mandioca', 'Molho inglês', 5, 2, 'TABLESPOON', 'para temperar'),
    ('Carne de panela com mandioca', 'Páprica doce', 6, 2, 'TEASPOON', 'para temperar'),
    ('Carne de panela com mandioca', 'Caldo de carne', 7, 1, 'LITER', 'quente'),
    ('Moqueca de peixe e camarão', 'Filé de peixe branco', 1, 800, 'GRAM', 'em postas grandes'),
    ('Moqueca de peixe e camarão', 'Camarão', 2, 500, 'GRAM', 'limpo'),
    ('Moqueca de peixe e camarão', 'Óleo de coco', 3, 1, 'TABLESPOON', 'para refogar'),
    ('Moqueca de peixe e camarão', 'Azeite de dendê', 4, 3, 'TABLESPOON', 'adicionado gradualmente'),
    ('Moqueca de peixe e camarão', 'Pimentão amarelo', 5, 2, 'UNIT', 'em tiras'),
    ('Moqueca de peixe e camarão', 'Coentro fresco', 6, 0.5, 'CUP', 'folhas e talos picados'),
    ('Moqueca de peixe e camarão', 'Limão-taiti', 7, 3, 'UNIT', 'suco para temperar'),
    ('Salmão com cevada e aspargos', 'Salmão', 1, 800, 'GRAM', 'em quatro porções'),
    ('Salmão com cevada e aspargos', 'Aspargo', 2, 2, 'UNIT', 'maços, bases removidas'),
    ('Salmão com cevada e aspargos', 'Endro', 3, 2, 'TABLESPOON', 'fresco, picado'),
    ('Salmão com cevada e aspargos', 'Alcaparra', 4, 2, 'TABLESPOON', 'escorrida'),
    ('Salmão com cevada e aspargos', 'Iogurte grego', 5, 200, 'GRAM', 'para o molho'),
    ('Salmão com cevada e aspargos', 'Alho em pó', 6, 0.5, 'TEASPOON', 'para o molho'),
    ('Salmão com cevada e aspargos', 'Cevada em grãos', 7, 250, 'GRAM', 'crua'),
    ('Espaguete ao pesto', 'Espaguete', 1, 500, 'GRAM', 'massa seca'),
    ('Espaguete ao pesto', 'Manjericão', 2, 2, 'CUP', 'folhas frescas compactadas'),
    ('Espaguete ao pesto', 'Pinoli', 3, 50, 'GRAM', 'levemente tostado'),
    ('Espaguete ao pesto', 'Queijo parmesão', 4, 80, 'GRAM', 'ralado fino'),
    ('Espaguete ao pesto', 'Azeite extravirgem', 5, 12, 'TABLESPOON', 'incorporado aos poucos'),
    ('Espaguete ao pesto', 'Pimenta-do-reino', 6, 0.5, 'TEASPOON', 'moída na hora'),
    ('Espaguete ao pesto', 'Queijo pecorino', 7, 40, 'GRAM', 'ralado fino'),
    ('Lasanha à bolonhesa', 'Massa para lasanha', 1, 500, 'GRAM', 'massa seca para 8 porções'),
    ('Lasanha à bolonhesa', 'Carne moída bovina', 2, 700, 'GRAM', 'para o molho bolonhesa'),
    ('Lasanha à bolonhesa', 'Ricota', 3, 350, 'GRAM', 'esfarelada entre as camadas'),
    ('Lasanha à bolonhesa', 'Muçarela', 4, 400, 'GRAM', 'fatiada ou ralada'),
    ('Lasanha à bolonhesa', 'Molho de tomate', 5, 1000, 'MILLILITER', 'para umedecer todas as camadas'),
    ('Lasanha à bolonhesa', 'Orégano', 6, 2, 'TEASPOON', 'para temperar o molho'),
    ('Lasanha à bolonhesa', 'Noz-moscada', 7, 0.5, 'TEASPOON', 'ralada na ricota'),
    ('Risoto de cogumelos', 'Arroz arbóreo', 1, 450, 'GRAM', 'peso cru para 6 porções'),
    ('Risoto de cogumelos', 'Cogumelo portobello', 2, 500, 'GRAM', 'fatiado e dourado'),
    ('Risoto de cogumelos', 'Caldo de legumes', 3, 1.5, 'LITER', 'quente, adicionar aos poucos'),
    ('Risoto de cogumelos', 'Vinho branco culinário', 4, 180, 'MILLILITER', 'para deglacear o arroz'),
    ('Risoto de cogumelos', 'Chalota', 5, 3, 'UNIT', 'picadas finamente'),
    ('Risoto de cogumelos', 'Queijo grana padano', 6, 120, 'GRAM', 'ralado para finalizar'),
    ('Risoto de cogumelos', 'Sálvia', 7, 2, 'TEASPOON', 'picada para finalizar'),
    ('Paella de frutos do mar', 'Arroz bomba', 1, 600, 'GRAM', 'peso cru para 8 porções'),
    ('Paella de frutos do mar', 'Lula', 2, 500, 'GRAM', 'limpa e cortada em anéis'),
    ('Paella de frutos do mar', 'Mexilhão', 3, 800, 'GRAM', 'com concha e bem higienizado'),
    ('Paella de frutos do mar', 'Chouriço espanhol', 4, 250, 'GRAM', 'fatiado para a base'),
    ('Paella de frutos do mar', 'Açafrão', 5, 0.5, 'TEASPOON', 'infusionado no caldo quente'),
    ('Paella de frutos do mar', 'Caldo de frutos do mar', 6, 1.5, 'LITER', 'quente, com o açafrão infusionado'),
    ('Paella de frutos do mar', 'Páprica defumada', 7, 2, 'TEASPOON', 'para temperar a base'),
    ('Omelete de presunto e queijo', 'Ovo de galinha', 1, 8, 'UNIT', 'dois ovos por porção'),
    ('Omelete de presunto e queijo', 'Presunto cozido', 2, 160, 'GRAM', 'picado para o recheio'),
    ('Omelete de presunto e queijo', 'Queijo cheddar', 3, 140, 'GRAM', 'ralado para o recheio'),
    ('Omelete de presunto e queijo', 'Cebolinha', 4, 4, 'TABLESPOON', 'fatiada e dividida entre as porções'),
    ('Omelete de presunto e queijo', 'Tomate seco', 5, 60, 'GRAM', 'escorrido e picado'),
    ('Omelete de presunto e queijo', 'Creme de leite', 6, 60, 'MILLILITER', 'para deixar os ovos macios'),
    ('Omelete de presunto e queijo', 'Óleo de canola', 7, 1, 'TABLESPOON', 'para untar a frigideira'),
    ('Panqueca americana', 'Farinha de trigo', 1, 300, 'GRAM', 'rende cerca de 12 panquecas'),
    ('Panqueca americana', 'Fermento químico', 2, 3, 'TEASPOON', 'niveladas para massa fofa'),
    ('Panqueca americana', 'Açúcar refinado', 3, 3, 'TABLESPOON', 'para adoçar levemente a massa'),
    ('Panqueca americana', 'Extrato de baunilha', 4, 2, 'TEASPOON', 'misturado aos líquidos'),
    ('Panqueca americana', 'Leitelho', 5, 500, 'MILLILITER', 'ajustar até obter massa espessa'),
    ('Panqueca americana', 'Óleo de girassol', 6, 2, 'TABLESPOON', 'para a massa e a frigideira'),
    ('Panqueca americana', 'Xarope de bordo', 7, 180, 'MILLILITER', 'para servir sobre as panquecas'),
    ('Pão integral com sementes', 'Farinha de trigo integral', 1, 500, 'GRAM', 'para um pão grande de 10 fatias'),
    ('Pão integral com sementes', 'Fermento biológico seco', 2, 2, 'TEASPOON', 'aproximadamente um sachê'),
    ('Pão integral com sementes', 'Água', 3, 350, 'MILLILITER', 'morna, ajustar conforme a farinha'),
    ('Pão integral com sementes', 'Sal marinho', 4, 1.5, 'TEASPOON', 'niveladas'),
    ('Pão integral com sementes', 'Gergelim', 5, 30, 'GRAM', 'na massa e na cobertura'),
    ('Pão integral com sementes', 'Semente de girassol', 6, 50, 'GRAM', 'na massa e na cobertura'),
    ('Pasta de feijão-branco', 'Feijão-branco', 1, 400, 'GRAM', 'peso seco antes do molho e cocção'),
    ('Pasta de feijão-branco', 'Tahine', 2, 4, 'TABLESPOON', 'para dar cremosidade'),
    ('Pasta de feijão-branco', 'Páprica picante', 3, 1, 'TEASPOON', 'ajustar à picância desejada'),
    ('Pasta de feijão-branco', 'Vinagre de maçã', 4, 2, 'TABLESPOON', 'para acidez equilibrada'),
    ('Pasta de feijão-branco', 'Za''atar', 5, 2, 'TEASPOON', 'para temperar a pasta'),
    ('Pasta de feijão-branco', 'Óleo de abacate', 6, 4, 'TABLESPOON', 'adicionar ao processar'),
    ('Guacamole com tortilhas', 'Abacate', 1, 3, 'UNIT', 'maduros e de tamanho médio'),
    ('Guacamole com tortilhas', 'Pimenta jalapeño', 2, 1, 'UNIT', 'sem sementes para menor ardor'),
    ('Guacamole com tortilhas', 'Cebola branca', 3, 0.5, 'UNIT', 'picada finamente'),
    ('Guacamole com tortilhas', 'Tomatillo', 4, 2, 'UNIT', 'picados para acidez e frescor'),
    ('Guacamole com tortilhas', 'Semente de abóbora', 5, 30, 'GRAM', 'tostada para finalizar'),
    ('Guacamole com tortilhas', 'Tortilha de milho', 6, 300, 'GRAM', 'cortada e tostada para servir'),
    ('Curry de tofu com macarrão de arroz', 'Tofu firme', 1, 500, 'GRAM', 'prensado e cortado em cubos'),
    ('Curry de tofu com macarrão de arroz', 'Acelga chinesa', 2, 300, 'GRAM', 'talos e folhas separados'),
    ('Curry de tofu com macarrão de arroz', 'Broto de bambu', 3, 200, 'GRAM', 'escorrido e fatiado'),
    ('Curry de tofu com macarrão de arroz', 'Missô', 4, 3, 'TABLESPOON', 'diluído sem ferver em excesso'),
    ('Curry de tofu com macarrão de arroz', 'Vinagre de arroz', 5, 2, 'TABLESPOON', 'para equilibrar o molho'),
    ('Curry de tofu com macarrão de arroz', 'Macarrão de arroz', 6, 300, 'GRAM', 'peso seco para 4 porções'),
    ('Lombo suíno agridoce', 'Lombo suíno', 1, 900, 'GRAM', 'em cubos para 6 porções'),
    ('Lombo suíno agridoce', 'Pêssego em conserva', 2, 300, 'GRAM', 'escorrido e cortado'),
    ('Lombo suíno agridoce', 'Ervilha-torta', 3, 300, 'GRAM', 'aparada e salteada brevemente'),
    ('Lombo suíno agridoce', 'Ketchup', 4, 120, 'MILLILITER', 'base do molho agridoce'),
    ('Lombo suíno agridoce', 'Açúcar mascavo', 5, 3, 'TABLESPOON', 'para adoçar e caramelizar'),
    ('Lombo suíno agridoce', 'Amido de milho', 6, 2, 'TABLESPOON', 'dissolvido antes de engrossar'),
    ('Cuscuz marroquino com cordeiro', 'Pernil de cordeiro', 1, 1.2, 'KILOGRAM', 'sem osso, em cubos'),
    ('Cuscuz marroquino com cordeiro', 'Cuscuz marroquino', 2, 600, 'GRAM', 'peso seco para 8 porções'),
    ('Cuscuz marroquino com cordeiro', 'Damasco seco', 3, 180, 'GRAM', 'picado e hidratado no cozimento'),
    ('Cuscuz marroquino com cordeiro', 'Amêndoa', 4, 120, 'GRAM', 'tostada e laminada'),
    ('Cuscuz marroquino com cordeiro', 'Ras el hanout', 5, 2, 'TABLESPOON', 'para temperar o cordeiro'),
    ('Cuscuz marroquino com cordeiro', 'Harissa', 6, 2, 'TABLESPOON', 'servir à parte ou no molho'),
    ('Sanduíche integral de atum', 'Atum em conserva', 1, 320, 'GRAM', 'peso drenado para 4 sanduíches'),
    ('Sanduíche integral de atum', 'Pão de forma integral', 2, 8, 'UNIT', 'fatias, duas por sanduíche'),
    ('Sanduíche integral de atum', 'Maionese', 3, 4, 'TABLESPOON', 'misturada ao atum'),
    ('Sanduíche integral de atum', 'Pepino em conserva', 4, 100, 'GRAM', 'escorrido e fatiado'),
    ('Sanduíche integral de atum', 'Alface romana', 5, 80, 'GRAM', 'folhas lavadas e bem secas'),
    ('Sanduíche integral de atum', 'Queijo provolone', 6, 120, 'GRAM', 'fatiado, cerca de 30 g por porção'),
    ('Bolo de chocolate sem trigo', 'Cacau em pó', 1, 80, 'GRAM', 'peneirado com os secos'),
    ('Bolo de chocolate sem trigo', 'Chocolate amargo', 2, 200, 'GRAM', 'derretido para a massa'),
    ('Bolo de chocolate sem trigo', 'Farinha de amêndoa', 3, 220, 'GRAM', 'base seca sem trigo'),
    ('Bolo de chocolate sem trigo', 'Açúcar de coco', 4, 180, 'GRAM', 'para adoçar a massa'),
    ('Bolo de chocolate sem trigo', 'Creme de coco', 5, 250, 'MILLILITER', 'para umidade e gordura'),
    ('Bolo de chocolate sem trigo', 'Bicarbonato de sódio', 6, 1, 'TEASPOON', 'nivelada e misturada aos secos'),
    ('Cheesecake de maracujá', 'Cream cheese', 1, 600, 'GRAM', 'em temperatura ambiente'),
    ('Cheesecake de maracujá', 'Biscoito integral', 2, 250, 'GRAM', 'triturado para a base'),
    ('Cheesecake de maracujá', 'Leite condensado', 3, 395, 'MILLILITER', 'uma embalagem para o recheio'),
    ('Cheesecake de maracujá', 'Maracujá', 4, 4, 'UNIT', 'polpa para recheio e cobertura'),
    ('Cheesecake de maracujá', 'Gelatina incolor', 5, 12, 'GRAM', 'hidratada conforme a embalagem'),
    ('Cheesecake de maracujá', 'Castanha de caju', 6, 100, 'GRAM', 'triturada junto à base'),
    ('Chili vegetariano', 'Feijão-vermelho', 1, 300, 'GRAM', 'peso seco antes do molho'),
    ('Chili vegetariano', 'Feijão-carioca', 2, 300, 'GRAM', 'peso seco antes do molho'),
    ('Chili vegetariano', 'Trigo para quibe', 3, 200, 'GRAM', 'peso seco, previamente hidratado'),
    ('Chili vegetariano', 'Pimenta chipotle', 4, 2, 'TEASPOON', 'ajustar à picância desejada'),
    ('Chili vegetariano', 'Cerveja escura', 5, 500, 'MILLILITER', 'para cozinhar e encorpar o caldo'),
    ('Chili vegetariano', 'Levedura nutricional', 6, 4, 'TABLESPOON', 'para finalizar com sabor umami')
) AS seed(recipe_name, ingredient_name, position, quantity, unit, notes)
JOIN euchef_inserted_seed_recipes recipe ON recipe.name = seed.recipe_name
JOIN ingredients ingredient ON LOWER(ingredient.name) = LOWER(seed.ingredient_name);

INSERT INTO recipe_steps (recipe_id, position, instruction)
SELECT recipe.id, seed.position, seed.instruction
FROM (VALUES
    ('Ratatouille provençal', 1, 'Corte os legumes em fatias uniformes e aqueça o forno a 200 °C.'),
    ('Ratatouille provençal', 2, 'Disponha os legumes, regue com azeite e asse até ficarem macios.'),
    ('Ratatouille provençal', 3, 'Ajuste o tempero e sirva quente ou em temperatura ambiente.'),
    ('Sopa rústica de raízes', 1, 'Higienize, descasque quando necessário e corte os vegetais.'),
    ('Sopa rústica de raízes', 2, 'Cozinhe tudo em água suficiente até que as raízes estejam macias.'),
    ('Sopa rústica de raízes', 3, 'Bata parcialmente, ajuste a textura e sirva.'),
    ('Salada verde crocante', 1, 'Lave e seque cuidadosamente as folhas e os vegetais.'),
    ('Salada verde crocante', 2, 'Fatie pepino, rabanete e beterraba e misture às folhas.'),
    ('Salada verde crocante', 3, 'Tempere somente no momento de servir.'),
    ('Legumes salteados orientais', 1, 'Corte os legumes em tamanhos semelhantes.'),
    ('Legumes salteados orientais', 2, 'Salteie primeiro os legumes mais firmes e acrescente os demais aos poucos.'),
    ('Legumes salteados orientais', 3, 'Finalize quando estiverem cozidos, porém ainda crocantes.'),
    ('Salada de frutas tropical', 1, 'Lave, descasque e retire sementes quando necessário.'),
    ('Salada de frutas tropical', 2, 'Corte as frutas em cubos e misture delicadamente.'),
    ('Salada de frutas tropical', 3, 'Leve à geladeira e sirva no mesmo dia.'),
    ('Iogurte com frutas vermelhas', 1, 'Lave e seque as frutas com cuidado.'),
    ('Iogurte com frutas vermelhas', 2, 'Distribua o iogurte em taças e cubra com as frutas.'),
    ('Iogurte com frutas vermelhas', 3, 'Finalize com mel e chia imediatamente antes de servir.'),
    ('Mingau de aveia com pera', 1, 'Aqueça o leite com a aveia, mexendo para não grudar.'),
    ('Mingau de aveia com pera', 2, 'Acrescente pera, canela e uva-passa e cozinhe até engrossar.'),
    ('Mingau de aveia com pera', 3, 'Sirva com nozes e linhaça por cima.'),
    ('Tabule de quinoa', 1, 'Cozinhe a quinoa, escorra se necessário e deixe esfriar.'),
    ('Tabule de quinoa', 2, 'Pique os vegetais e as ervas e misture à quinoa.'),
    ('Tabule de quinoa', 3, 'Junte limão e romã, ajuste o tempero e sirva.'),
    ('Curry de lentilha', 1, 'Cozinhe o arroz integral separadamente até ficar macio.'),
    ('Curry de lentilha', 2, 'Cozinhe a lentilha com leite de coco e especiarias até encorpar.'),
    ('Curry de lentilha', 3, 'Ajuste o tempero e sirva o curry com o arroz.'),
    ('Feijão-preto com acompanhamentos', 1, 'Deixe o feijão de molho e cozinhe com o louro até ficar macio.'),
    ('Feijão-preto com acompanhamentos', 2, 'Doure bacon e linguiça, incorpore ao feijão e apure o caldo.'),
    ('Feijão-preto com acompanhamentos', 3, 'Sirva com couve refogada e farinha de mandioca.'),
    ('Frango assado com mostarda', 1, 'Marine o frango com mostarda, vinho e ervas.'),
    ('Frango assado com mostarda', 2, 'Distribua o frango e as batatas em assadeira e acrescente a manteiga.'),
    ('Frango assado com mostarda', 3, 'Asse até o centro do frango atingir cocção segura e deixe descansar antes de servir.'),
    ('Carne de panela com mandioca', 1, 'Sele a carne em porções para dourar de maneira uniforme.'),
    ('Carne de panela com mandioca', 2, 'Junte temperos e caldo e cozinhe sob pressão até a carne amaciar.'),
    ('Carne de panela com mandioca', 3, 'Acrescente mandioca e quiabo e finalize até os vegetais ficarem macios.'),
    ('Moqueca de peixe e camarão', 1, 'Tempere peixe e camarão com limão e reserve sob refrigeração.'),
    ('Moqueca de peixe e camarão', 2, 'Cozinhe o pimentão com os óleos até amaciar.'),
    ('Moqueca de peixe e camarão', 3, 'Adicione os frutos do mar e cozinhe somente até ficarem opacos; finalize com coentro.'),
    ('Salmão com cevada e aspargos', 1, 'Cozinhe a cevada até ficar macia e escorra.'),
    ('Salmão com cevada e aspargos', 2, 'Asse o salmão e os aspargos até o ponto desejado.'),
    ('Salmão com cevada e aspargos', 3, 'Misture iogurte, endro, alcaparra e alho e sirva com o peixe.'),
    ('Espaguete ao pesto', 1, 'Cozinhe o espaguete em água fervente até ficar al dente.'),
    ('Espaguete ao pesto', 2, 'Processe manjericão, pinoli, queijos e azeite até formar um molho.'),
    ('Espaguete ao pesto', 3, 'Misture o pesto à massa fora do fogo e finalize com pimenta.'),

    ('Lasanha à bolonhesa', 1, 'Cozinhe a carne com o molho de tomate até apurar.'),
    ('Lasanha à bolonhesa', 2, 'Monte camadas de massa, molho, ricota e muçarela.'),
    ('Lasanha à bolonhesa', 3, 'Asse até borbulhar e deixe descansar antes de cortar.'),
    ('Risoto de cogumelos', 1, 'Mantenha o caldo aquecido e refogue chalota e cogumelos.'),
    ('Risoto de cogumelos', 2, 'Toste o arroz, junte vinho e acrescente o caldo aos poucos, mexendo.'),
    ('Risoto de cogumelos', 3, 'Finalize com queijo e sálvia quando o arroz estiver cremoso e al dente.'),
    ('Paella de frutos do mar', 1, 'Doure o chouriço e prepare a base temperada na paellera.'),
    ('Paella de frutos do mar', 2, 'Adicione o arroz e o caldo quente com açafrão, sem mexer em excesso.'),
    ('Paella de frutos do mar', 3, 'Disponha lula e mexilhão e cozinhe até o arroz absorver o caldo.'),
    ('Omelete de presunto e queijo', 1, 'Bata os ovos com o creme de leite.'),
    ('Omelete de presunto e queijo', 2, 'Aqueça o óleo, despeje os ovos e distribua o recheio.'),
    ('Omelete de presunto e queijo', 3, 'Dobre quando as bordas firmarem e cozinhe até o centro atingir ponto seguro.'),
    ('Panqueca americana', 1, 'Misture separadamente os ingredientes secos e os líquidos.'),
    ('Panqueca americana', 2, 'Una as misturas sem bater em excesso.'),
    ('Panqueca americana', 3, 'Doure pequenas porções em frigideira e sirva com xarope.'),
    ('Pão integral com sementes', 1, 'Misture os ingredientes e sove até obter massa elástica.'),
    ('Pão integral com sementes', 2, 'Deixe fermentar coberta até dobrar de volume e modele.'),
    ('Pão integral com sementes', 3, 'Asse até dourar e espere esfriar antes de cortar.'),
    ('Pasta de feijão-branco', 1, 'Cozinhe o feijão até ficar muito macio e escorra.'),
    ('Pasta de feijão-branco', 2, 'Processe com tahine, vinagre, especiarias e óleo.'),
    ('Pasta de feijão-branco', 3, 'Ajuste a textura com água potável e conserve sob refrigeração.'),
    ('Guacamole com tortilhas', 1, 'Amasse o abacate e pique finamente os vegetais.'),
    ('Guacamole com tortilhas', 2, 'Misture tudo e ajuste o tempero.'),
    ('Guacamole com tortilhas', 3, 'Finalize com sementes e sirva imediatamente com as tortilhas.'),
    ('Curry de tofu com macarrão de arroz', 1, 'Hidrate ou cozinhe o macarrão conforme a embalagem.'),
    ('Curry de tofu com macarrão de arroz', 2, 'Doure o tofu e salteie a acelga e o broto de bambu.'),
    ('Curry de tofu com macarrão de arroz', 3, 'Dilua o missô com vinagre, envolva os ingredientes e sirva com o macarrão.'),
    ('Lombo suíno agridoce', 1, 'Corte e doure o lombo até atingir cocção segura.'),
    ('Lombo suíno agridoce', 2, 'Junte pêssego e ervilha-torta e cozinhe brevemente.'),
    ('Lombo suíno agridoce', 3, 'Misture ketchup, açúcar e amido dissolvido e cozinhe até engrossar.'),
    ('Cuscuz marroquino com cordeiro', 1, 'Sele o cordeiro e cozinhe lentamente com as especiarias até amaciar.'),
    ('Cuscuz marroquino com cordeiro', 2, 'Hidrate o cuscuz e solte os grãos com um garfo.'),
    ('Cuscuz marroquino com cordeiro', 3, 'Misture damasco e amêndoa e sirva com o cordeiro e harissa.'),
    ('Sanduíche integral de atum', 1, 'Escorra o atum e misture com a maionese.'),
    ('Sanduíche integral de atum', 2, 'Distribua folhas, pasta de atum, pepino e queijo sobre o pão.'),
    ('Sanduíche integral de atum', 3, 'Feche, corte e mantenha refrigerado até servir.'),
    ('Bolo de chocolate sem trigo', 1, 'Aqueça o forno e misture os ingredientes secos.'),
    ('Bolo de chocolate sem trigo', 2, 'Derreta o chocolate, junte o creme e incorpore aos secos.'),
    ('Bolo de chocolate sem trigo', 3, 'Asse até o centro firmar e deixe esfriar antes de servir.'),
    ('Cheesecake de maracujá', 1, 'Triture biscoitos e castanhas e compacte a base.'),
    ('Cheesecake de maracujá', 2, 'Misture cream cheese e leite condensado e incorpore a gelatina preparada.'),
    ('Cheesecake de maracujá', 3, 'Refrigere até firmar e cubra com a polpa de maracujá.'),
    ('Chili vegetariano', 1, 'Deixe os feijões de molho e cozinhe até ficarem macios.'),
    ('Chili vegetariano', 2, 'Junte trigo, chipotle e cerveja e cozinhe até o caldo encorpar.'),
    ('Chili vegetariano', 3, 'Finalize com levedura nutricional e ajuste o tempero.')
) AS seed(recipe_name, position, instruction)
JOIN euchef_inserted_seed_recipes recipe ON recipe.name = seed.recipe_name;
