CREATE TABLE weekly_plan_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
    week_start DATE NOT NULL,
    recipe_id BIGINT NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_weekly_plan_entries_monday CHECK (EXTRACT(ISODOW FROM week_start) = 1),
    CONSTRAINT uk_weekly_plan_entries_user_week_recipe UNIQUE (user_id, week_start, recipe_id)
);

CREATE INDEX ix_weekly_plan_entries_user_week
    ON weekly_plan_entries (user_id, week_start);
